import React, { useState, useEffect } from 'react';
import { CheckCircle2, XCircle, Clock, ShieldCheck, RefreshCw, Edit3 } from 'lucide-react';
import { ApprovalItem } from '../types';
import { fetchApprovals, reviewApproval } from '../api';

export const ApprovalsView: React.FC = () => {
  const [approvals, setApprovals] = useState<ApprovalItem[]>([]);
  const [statusFilter, setStatusFilter] = useState<string>('pending');
  const [loading, setLoading] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editQty, setEditQty] = useState<number>(0);

  const loadApprovals = async () => {
    setLoading(true);
    try {
      const data = await fetchApprovals(statusFilter === 'all' ? undefined : statusFilter);
      setApprovals(data);
    } catch (err) {
      console.error('Failed to load approvals:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadApprovals();
  }, [statusFilter]);

  const handleAction = async (item: ApprovalItem, action: 'approved' | 'rejected') => {
    const finalQty = editingId === item.id ? editQty : undefined;
    try {
      await reviewApproval(item.id, action, 'supply_chain_manager', finalQty);
      setEditingId(null);
      loadApprovals();
    } catch (err) {
      console.error('Action failed:', err);
    }
  };

  return (
    <div className="page-body">
      <div className="glass-panel" style={{ padding: '24px' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '20px',
            flexWrap: 'wrap',
            gap: '12px',
          }}
        >
          <div>
            <h2 style={{ fontSize: '18px', fontWeight: 600, color: '#fff' }}>
              Human-in-the-Loop Approval Queue
            </h2>
            <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '2px' }}>
              Verify AI-recommended purchase orders and inter-warehouse stock transfers before execution
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="form-select"
            >
              <option value="pending">Pending Review</option>
              <option value="approved">Approved History</option>
              <option value="rejected">Rejected History</option>
              <option value="all">All Proposals</option>
            </select>

            <button className="btn btn-secondary" onClick={loadApprovals}>
              <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
            </button>
          </div>
        </div>

        {loading ? (
          <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
            Loading approval queue items...
          </div>
        ) : approvals.length === 0 ? (
          <div style={{ padding: '50px', textAlign: 'center', color: 'var(--text-muted)' }}>
            <ShieldCheck size={36} color="#6366f1" style={{ marginBottom: '12px' }} />
            <div>No items in the {statusFilter} approval queue.</div>
            <div style={{ fontSize: '12px', marginTop: '4px' }}>
              New proposals generated by the AI copilot or replenishment engine will appear here.
            </div>
          </div>
        ) : (
          <div className="table-container">
            <table className="custom-table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Action Type</th>
                  <th>SKU</th>
                  <th>Warehouse</th>
                  <th>Units</th>
                  <th>AI Reasoning</th>
                  <th>Status</th>
                  <th>Decision</th>
                </tr>
              </thead>
              <tbody>
                {approvals.map((item) => (
                  <tr key={item.id}>
                    <td style={{ color: 'var(--text-muted)' }}>#{item.id}</td>
                    <td style={{ fontWeight: 600, color: '#38bdf8' }}>
                      {item.recommendation_type}
                    </td>
                    <td style={{ fontWeight: 600, color: '#fff' }}>{item.sku_id}</td>
                    <td>{item.warehouse_id}</td>
                    <td>
                      {editingId === item.id ? (
                        <input
                          type="number"
                          value={editQty}
                          onChange={(e) => setEditQty(Number(e.target.value))}
                          className="form-input"
                          style={{ width: '80px', padding: '4px 8px' }}
                        />
                      ) : (
                        <span style={{ fontWeight: 700 }}>
                          {item.edited_quantity ?? item.quantity}
                        </span>
                      )}
                    </td>
                    <td style={{ maxWidth: '300px', fontSize: '12px', lineHeight: 1.4 }}>
                      {item.ai_reasoning}
                    </td>
                    <td>
                      <span
                        className={`badge ${
                          item.status === 'approved'
                            ? 'badge-healthy'
                            : item.status === 'rejected'
                            ? 'badge-critical'
                            : 'badge-warning'
                        }`}
                      >
                        {item.status.toUpperCase()}
                      </span>
                    </td>
                    <td>
                      {item.status === 'pending' ? (
                        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                          <button
                            className="btn btn-success"
                            style={{ padding: '5px 10px', fontSize: '11px' }}
                            onClick={() => handleAction(item, 'approved')}
                          >
                            <CheckCircle2 size={13} />
                            <span>Approve</span>
                          </button>
                          <button
                            className="btn btn-danger"
                            style={{ padding: '5px 10px', fontSize: '11px' }}
                            onClick={() => handleAction(item, 'rejected')}
                          >
                            <XCircle size={13} />
                            <span>Reject</span>
                          </button>
                          <button
                            className="btn btn-secondary"
                            style={{ padding: '5px', fontSize: '11px' }}
                            title="Edit quantity"
                            onClick={() => {
                              setEditingId(item.id);
                              setEditQty(item.quantity);
                            }}
                          >
                            <Edit3 size={13} />
                          </button>
                        </div>
                      ) : (
                        <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                          Reviewed by {item.reviewed_by || 'system'}
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};
